import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Dashboard from '../components/Dashboard'
import data from '../data.json'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Time Tracking Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
      <h1>data.title</h1>
    </div>
  )
}
